# Travis Build File
language: java
jdk:
  - oraclejdk8
before_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn clean compile test
notifications:
  email:
    - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true